### PR TITLE
[TASK] Disable tcpdf watermark by default

### PR DESCRIPTION
**Pull request by liayn**

### CODE REVIEW

**Comment by maechler** [comment]
@liayn Closing here in favor of https://github.com/bithost-gmbh/pdfviewhelpers/pull/206 which had no conflicts and an additional feature. Thank you very much nevertheless!

**Comment by liayn** [comment]
Which is a pity, because by reading it is full of non PSR-2 code quality and so on. :-(

**Comment by maechler** [comment]
I refactored the code before the release (https://github.com/bithost-gmbh/pdfviewhelpers/commit/19c987d0d9c8e803ff640e209587fa3dc620df2e), but please let me know if you have any concerns regarding this.

**Comment by liayn** [comment]
Okay. Still we have `(boolean) ...` in there and stuff like this. => should be `(bool)` (and no space), for instance.
But maybe this should be done in a dedicated cleanup.
Thanks for getting this on the road, because I can now drop my fork again ✔

**Comment by maechler** [comment]
No worries, thank you for the contributions and I agree with the dedicated cleanup 👍

**Pull request closed without merging**
