### PR TITLE
Insert Line Feed for each paragraph

### PR DESCRIPTION
**Pull request by emmemme**
Insert LF to each paragraph and disable justification in last line of the paragraph where align is "justify".

Before:
paragraphLF-before

After:
paragraphLF-after

### CODE REVIEW

**Comment by macjohnny** [comment]
thanks for your contribution, sounds good.

**Comment by macjohnny** [comment]
@emmemme could you please add the new parameter to https://github.com/bithost-gmbh/pdfviewhelpers/blob/master/Documentation/ViewHelpers/TextViewHelper/Index.rst ?

**Comment by emmemme** [comment]
Thanks for your code! M

**Comment by maechler** [comment]
Thanks @emmemme for your contribution! That looks like a very useful setting to be added!

There are however a few things that still need to be done until this could be released:

- Please rename the setting to `paragraphLineFeed`, as we try to avoid abbreviations
- The property needs to be added to `AbstractTextViewHelper::$mergeProperties` in order to support the settings inheritance
- It should be added to `setup.txt` with default value `0` for `generalText` and empty for `text`, `headline` and `list` (similar to other text properties)
- It should also be added to `Documentation/ConfigurationReference/TypoScriptReference/Index.rst` the same way other text properties such as `trim` are added
- The attribute should also be added to the template in `Documentation/ViewHelpers/HeadlineViewHelper/Index.rst` and `Documentation/ViewHelpers/ListViewHelper/Index.rst`
- It would be nice if you could squash all the commits into one single commit using `git reset --soft HEAD~3` and `git commit` (replace `3` with the number of commits you want to squash): https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git
- In addition the XML schema needs to be recompiled (I will take care of this)

If you have time to address these todos that would be awesome! Else I will try to take care of this when I work on some of the other issues in the upcoming days or weeks.

**Comment by emmemme** [comment]
I'll do it during the next weekend... no problem.

**Comment by maechler** [comment]
@emmemme Looks perfect to me! 😍 Thank you very much for your contribution!

If you like the project, please consider giving it a star :)

**Pull request merged**
