### PR TITLE
Adds TYPO3 9 LTS to test matrix

### PR DESCRIPTION
**Pull request by maechler**

### CODE REVIEW

**Comment by macjohnny** [comment]
looks similar to https://github.com/georgringer/news/blob/master/.travis.yml, so why do the tests fail? composer cache needs to be updated?

**Comment by macjohnny** [comment]
see also https://stackoverflow.com/questions/51422094/typo3-cms-version-9-installation-fails-due-to-lexer-missing

**Comment by maechler** [comment]
The tests also fail for the `news` extension: https://travis-ci.org/georgringer/news/builds/435983429

I already tried this `require lexer` fix, but it did not work in the past, but we could try it again.

**Comment by maechler** [comment]
@macjohnny thanks!

**Comment by macjohnny** [comment]
typo3 9.2.1 was used due to a version constraint of `"nimut/testing-framework": "^3.0"`. Allowing `"nimut/testing-framework": "^4.0"` fixed the issue

**Pull request merged**
