### PR TITLE
Added paragraphLineFeed param to Text, Headline and List viewhelpers

### PR DESCRIPTION
**Pull request by emmemme**
I've made all the updates, but I don't know how to merge this commit the preview pull request... so I'll create a new pull request with all updates.

### CODE REVIEW

**Comment by emmemme** [comment]
Sorry, I miss your messages in the original pull request... ops!

**Comment by maechler** [comment]
@emmemme It is a very useful feature and nicely implemented, thanks again! I would like to work on two other features in the upcoming two weeks and then release a new version including your feature.

**Comment by emmemme** [comment]
Thanks. I'll use this ext in a project in the next weeks. if I can help you, write to me. thanks again.

**Comment by maechler** [comment]
@emmemme If you need your feature to be available on Packagist or TER soon just let me know. If so, I will create two separate releases, one with your feature and one probably some weeks later with the other features.

**Pull request closed without merging**
