### PR TITLE
[BUGFIX] PHP 8 adjustments

### PR DESCRIPTION
**Pull request by liayn**

### CODE REVIEW

**Comment by maechler** [comment]
@liayn Thank you very much for your contributions! I am sorry I couldn't have a detailed look at it yet and I probably won't until second half of January. Merry Christmas 🎄

**Comment by liayn** [comment]
Well, that's perfectly fine. But you can actually safely merge this into master. It won't affect existing releases anyway and can't make things worse for those who need to use current systems. ;-)
(We are on production with this, just to let you know.)

Merry Christmas

**Review by maechler — APPROVED** [review]
Looks good to me, thank you very much!

**Comment by maechler** [comment]
@liayn I just created a new release `v2.5.0` containing your fixes, thanks again!

**Pull request merged**
